on:
  push:
    branches:
      - main
name: build
permissions:
  contents: write
jobs:
  build:
    name: run build script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: run ./setup.sh
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ./setup.sh

      - name: run ./deploy.sh
        run: ./deploy.sh
